name: Release Tarball

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential autotools-dev autoconf automake

      - name: Run make dist
        run: autoreconf -vif && ./configure && make dist

      - name: Find tarball
        id: find_tarball
        run: |
          file=$(ls *.tar.* | head -n1)
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ steps.find_tarball.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
