name: Release Tarball

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Run make dist
        run: nix develop .# --command bash -c "autoreconf -vif && ./configure && make dist"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
